### ISSUE TITLE
Configure Travis for ohsu-team-2

### ISSUE THREAD

**Issue by ksclarke** [RepoCamp/ohsu-team-2#1]
Create a Travis config that can be used to run the ohsu-team-2 test suite and configure the build to run within Travis.

**Comment by ksclarke** [comment]
We can crib from the Hyrax Travis configuration: https://github.com/samvera/hyrax/blob/master/.travis.yml

**Comment by evanwill** [comment]
need `rails hyrax:default_admin_set:create` ?
