### ISSUE TITLE
Set up audio work type

### ISSUE THREAD

**Issue by mspalti** [RepoCamp/ohsu-team-2#9]
- [x] research!
- [x] implement!

**Comment by ksclarke** [comment]
Something changed and now spec wants firefox instead of chrome for webdriver.

Installed Firefox webdriver from: https://github.com/mozilla/geckodriver/releases
and then also installed Firefox on the system

Not sure why things switched from using Chrome to wanting to use Firefox.

'''
  1) Create a AudioWork a logged in user 
     Failure/Error: visit '/dashboard'
     
     Selenium::WebDriver::Error::UnknownError:
       Process unexpectedly closed with status 1
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/marionette/driver.rb:50:in `initialize'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:23:in `browser'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:49:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/capybara-2.18.0/lib/capybara/session.rb:274:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/create_audio_work_spec.rb:34:in `block (3 levels) in <top (required)>'

'''

**Comment by ksclarke** [comment]
Rather than trying to configure Capybara, our product manager suggests we keep Javascript off and go directly to the create audiowork page rather than going through the Javascript modal.

**Comment by evanwill** [comment]
closed by PR #19
